# Generated by Django 4.2.7 on 2023-11-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thenewapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='des',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name1',
            new_name='name',
        ),
    ]
